### ISSUE TITLE
Change the visual_size of the object if the item has a wield_scale

### ISSUE THREAD

**Issue by HybridDog** [stujones11/wield3d#1]
[According to GreenDimond](https://forum.minetest.net/viewtopic.php?p=220557#p220557), the size of the wield3d object is not affected by the wield_scale of an item.

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3347
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3429

The object may need to be put to a different position relative to the player because the position may be the center of the object and it stretches in every direction if visual_size is changed.

**Comment by stujones11** [comment]
The relative positioning was the thing that put me off adding support for scale, iirc, getting the positions to look correct was rather tricky. I might look at it again when I get time.

**Comment by stujones11** [comment]
Support for visual scale override has been added in cc9124a847b9507fc70b30a0b9ef12fad4160d3f this can be used in the same way as rotation and position can be overridden, which will likely be required if the scale is changed from the default.

Since it would be overly complex to automatically reposition the item depending on scale I will close this issue now but feel free to make a new issue or PR if you can find a better solution.
